### ISSUE TITLE
Stop Process By ID

### ISSUE THREAD

**Issue by blaxroze** [cocur/background-process#11]
How to stop process by ID?
I am using stable version.
Thanks.

<pre>
$process = new BackgroundProcess('/usr/bin/php queue.php');
        if ($process->isRunning(15371)) {
            $process->stop();
        }
</pre>

**Comment by florianeckerstorfer** [comment]
`BackgroundProcess` handles the PID internally. The parameter you passed to `isPassing()` does actually do nothing. If you want to stop a process manually by PID you can check out the source code of the `stop()` method. See https://github.com/cocur/background-process/blob/master/src/BackgroundProcess.php#L94
